### ISSUE TITLE
作者你好，提示 成功! 200 ，然后程序中断

### ISSUE THREAD

**Issue by hehekeke** [lonerge/tiktok_youtube_douyin_handling#2]
<img width="1727" alt="image" src="https://user-images.githubusercontent.com/8870314/222958607-6be11da9-fe62-414d-9034-0c976467deb9.png">
请问是怎么回事呢哈

**Comment by lonerge** [comment]
fixed

**Comment by hehekeke** [comment]
感谢，已经生效了
