### ISSUE TITLE
下载视频异常

### ISSUE THREAD

**Issue by xingyuezhiji** [lonerge/tiktok_youtube_douyin_handling#5]
下载视频异常: [Errno 2] No such file or directory: 'D:\\tiktok\\douyin_login\\videos\\7110821272342351135.mp4'

**Comment by lonerge** [comment]
修改配置文件config.ini, 路径换成自己电脑路径

**Comment by xingyuezhiji** [comment]
> 

已经修改了的，是不支持自动创建目录吗

**Comment by lonerge** [comment]
自己加吧, 不支持

**Comment by xingyuezhiji** [comment]
> 自己加吧, 不支持

好的哈，谢谢~
